### ISSUE TITLE
感谢作者库提供的灵感，已将虚拟瀑布流提取成组件

### ISSUE THREAD

**Issue by lhlyu** [orilights/PixivCollection#1]
- [vue-virtual-waterfall](https://github.com/lhlyu/vue-virtual-waterfall)

邀请作者一起维护

**Comment by orilights** [comment]
很抱歉最近我没什么空闲时间能参与开发，等之后有时间了我再看看有什么能帮得上忙的地方吧😂

**Comment by orilights** [comment]
另外我这虚拟列表本身写的也不咋样，只是勉强实现了功能，没做什么优化，数据多滑的快一点掉帧白屏情况十分严重，或许可以再找找有没有什么更好的实现

**Comment by lhlyu** [comment]
我想问个问题，不定高的那种虚拟瀑布流要怎么弄

**Comment by orilights** [comment]
> 我想问个问题，不定高的那种虚拟瀑布流要怎么弄

这个好像没啥好办法，没办法提前计算内容高度的话只能让前面的所有内容加载完再获取高度进行排序，内容是纯文字的话还好，带图片之类的的话一次性加载全部的内容不现实

单列不定高内容可以先给个默认高度让内容加载完后拿到高度再计算偏移，瀑布流的话因为前面的内容高度发生变化要重新排序用不了这种方法

**Comment by orilights** [comment]
> 我想问个问题，不定高的那种虚拟瀑布流要怎么弄

https://zhuanlan.zhihu.com/p/444778554

这里面有单列不定高虚拟列表的实现，但瀑布流这种多列内容我没有想到或找到什么好办法
